@host = http://3.120.74.192:9090/rest
@token = {{obtainToken.response.body.$.authToken}}

# @name obtainToken
POST {{host}}/authentication
Content-Type: application/json

{
  "email" : "tmp-email-1583153349316@mail.ru",
  "password" : "tmpPassword"
}​​

###
GET {{host}}/news?start=0&count=15&accepted=all
Content-Type: application/json
Authorization: {{token}}

{}

###
GET {{host}}/films/326
Content-Type: application/json
Authorization: {{token}}

{}

###
GET {{host}}/news/38/accept
Content-Type: application/json
Authorization: {{token}}

{}

###
GET {{host}}/api/users/list
Content-Type: application/json
Authorization: {{token}}

###
POST {{host}}/textnews/add
Content-Type: application/json
Authorization: {{token}}

{
  "title" : "gago",
  "descriptioin" : "gagagg",
  "url" : "the url"
 }
